<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class GoalAction extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * @var array
     */
    public $fillable = [
        'title',
        'goalId',
        'startDateTime',
        'weekDays',
        'addToTodoList',
    ];

    /**
     *
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::saving(function ($row) {
            $row->weekDays = implode(',', $row->weekDays);
        });
    }

    /**
     * Get goal
     * @return object
     */
    public function goal(): object
    {
        return $this->belongsTo(Goal::class, 'goalId', 'id');
    }
}
