<?php

namespace Modules\Store\Entities;

use App\Traits\AppModelAwareTrait;
use App\Traits\UtilsTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Modules\Common\Traits\AttachmentsAwareTrait;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class ProductOptions extends Model implements HasMedia
{
    use AppModelAwareTrait,
        SoftDeletes,
        HasMediaTrait,
        AttachmentsAwareTrait,
        UtilsTrait;

    /**
     * @var array
     */
    public $attachments = [
        'optionImage' => [
            'clearBeforeSave' => true
        ]
    ];

    /**
     * @var array
     */
    protected $fillable = [
        'isAvailable',
        'productParamId',
        'productId',
        'optionKey',
        'optionLabel',
        'price',
        'catalogNumber',
        'barCode',
        'availableCount',
    ];


    /**
     *
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($row) {
            $row->price = $row->floatToInt($row->price);
        });

        static::saving(function ($row) {
            $changes = $row->getChanges();
            if (isset($changes['price'])) {
                $row->price = $row->floatToInt($row->price);
            }
        });
    }
}
